server:
  port: 8082
spring:
  application:
    name: execution-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
matching-engine:
  host: ${MATCHING_ENGINE_HOST:localhost}
  port: ${MATCHING_ENGINE_PORT:50051}
